"""Centralized secret redaction.

Two independent defenses, both applied to every log record and (per
security/SECRET_HANDLING.md) reused later by the audit writer:

1. Key denylist — a field whose *name* looks secret-shaped is redacted
   regardless of its value's shape. This is the primary control.
2. Value-pattern matching — a value that *looks* like a secret (a JWT, a
   long hex/base64 token) is redacted even under an innocuous key name.
   This is defense-in-depth, not the primary control.

Deliberate scope boundary: the value-pattern regexes exclude hyphens from
the "high entropy" character class. A canonical UUID (8-4-4-4-12 hex
digits with hyphens) is 36 characters and would otherwise match a generic
"long alnum+hyphen run" pattern — and this platform logs UUIDs
(correlation_id, event_id, proposal_id, ...) constantly and *deliberately*,
per docs/OBSERVABILITY.md. Excluding hyphens means a UUID's longest
hyphen-free run is 12 characters, well under the 32-character threshold, so
IDs pass through untouched while genuine hex/base64 secrets (which don't
have hyphens at fixed positions) are still caught. A URL-safe-base64 token
that happens to contain a hyphen is not guaranteed to be caught by pattern
matching alone — the key denylist is what's relied on for that case, which
is why the denylist uses substring matching (see `_looks_like_secret_key`)
rather than an exact-name list.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, MutableMapping
from typing import Any

REDACTED = "***REDACTED***"

# Substring match, not exact — catches "session_secret_key", "kite_api_key",
# "llm_api_key", "db_password", etc. without needing to enumerate every
# possible field name a future caller might choose.
_KEY_DENYLIST_TERMS: tuple[str, ...] = (
    "password",
    "secret",
    "token",
    "api_key",
    "apikey",
    "access_token",
    "authorization",
    "cookie",
    "csrf",
    "session_id",
)

# JWTs are base64url (hyphen/underscore allowed) but are identified by
# their highly characteristic "eyJ..." header prefix, not by length alone,
# so they don't collide with UUIDs despite allowing hyphens.
_JWT_PATTERN = re.compile(r"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b")

# Hex and standard (non-URL-safe) base64 only — no hyphen in the character
# class, so a 36-character hyphenated UUID never matches (see module
# docstring). Standard base64 also excludes underscore for the same reason
# secrets generated by common tooling (which typically doesn't guarantee
# avoiding '_') are still substantially covered by the hex pattern in
# practice, and by the key denylist regardless.
_HEX_PATTERN = re.compile(r"\b[0-9a-fA-F]{32,}\b")
_BASE64_PATTERN = re.compile(r"\b[A-Za-z0-9+/]{32,}={0,2}\b")


def _looks_like_secret_key(key: str) -> bool:
    lowered = key.lower()
    return any(term in lowered for term in _KEY_DENYLIST_TERMS)


def _redact_string_value(value: str) -> str:
    value = _JWT_PATTERN.sub(REDACTED, value)
    value = _HEX_PATTERN.sub(REDACTED, value)
    value = _BASE64_PATTERN.sub(REDACTED, value)
    return value


def _redact_any(value: Any) -> Any:  # genuinely accepts arbitrary log payload shapes
    if isinstance(value, str):
        return _redact_string_value(value)
    if isinstance(value, Mapping):
        return redact_mapping(value)
    if isinstance(value, list):
        return [_redact_any(item) for item in value]
    if isinstance(value, tuple):
        return tuple(_redact_any(item) for item in value)
    return value


def redact_mapping(mapping: Mapping[str, Any]) -> dict[str, Any]:
    """Redact a mapping: denylisted keys are wholly replaced, every other
    value is recursively scanned for secret-shaped substrings."""
    return {
        key: (REDACTED if _looks_like_secret_key(key) else _redact_any(value))
        for key, value in mapping.items()
    }


def redact_text(text: str) -> str:
    """Redact secret-shaped substrings in free text (e.g. a rendered
    exception traceback), independent of any key context."""
    return _redact_string_value(text)


def redact_processor(
    logger: object, method_name: str, event_dict: MutableMapping[str, Any]
) -> dict[str, Any]:
    """structlog processor. Must run last in the processor chain, immediately
    before the renderer — see atp_platform.logging."""
    return redact_mapping(event_dict)
